# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WunderDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  # Pods for WunderDemo
  ###Network
    pod 'Alamofire', '~> 4.7'
    pod 'RxAlamofire', '~> 5.0.0'
    pod 'AlamofireObjectMapper', '~> 5.2.1'
    
    ###Json Parse
    pod 'ObjectMapper', '~> 3.5'
    
    ###Rxswift
    pod 'RxSwift', '~> 5.1'
    pod 'RxCocoa', '~> 5.0'
    
    ###Localization
    pod 'Localize-Swift'
    
    target 'WunderDemoTests' do
    use_frameworks!
    
    # Pods for testing
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.2'
  
  
    inherit! :search_paths
    # Pods for testing
  end

  target 'WunderDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
